### ISSUE TITLE
v0.0.5 hasn't been published

### ISSUE THREAD

**Issue by hvent90** [census-instrumentation/opencensus-node#123]
Hi all,

I believe there was an intention to release v0.0.5 (https://github.com/census-instrumentation/opencensus-node/pull/118), however v0.0.4 is still the latest.

I apologize if I misunderstood and this issue is in error. Thanks!

**Comment by kjin** [comment]
It seems like it was published -- I see 0.0.5 here: https://www.npmjs.com/package/@opencensus/instrumentation-grpc

Let me know if that is not what you observe. You may need to manually install it if you are using a dependent of it, since those were not updated. Unfortunately releasing still sort of a manual process, so sorry about that!
