### ISSUE TITLE
createScopedRequired depcreated in google-auth-library 3.0.0

### ISSUE THREAD

**Issue by diiiego83** [census-instrumentation/opencensus-node#429]
### What version of OpenCensus are you using?
0.0.9

### What version of Node are you using?
8.11.3

(node:18) [google-auth-library:DEP003] DeprecationWarning: The `createScopedRequired` method on the `Compute` class has been deprecated, and will be removed in the 3.0 release of google-auth-library.

**Comment by mayurkale22** [comment]
Thanks for filling the issue.  This is what I found on [google-auth-library-nodejs](https://github.com/googleapis/google-auth-library-nodejs) repo.

The ```createScopedRequired``` and ```createScoped``` methods on the ```JWT``` class were largely in place to help inform clients when scopes were required in an application default credential scenario. Instead of checking if scopes are required after creating the client, instead scopes should just be passed either into the ```GoogleAuth.getClient``` method, or directly into the ```JWT``` constructor.

**Old code**
```
auth.getApplicationDefault(function(err, authClient) {
   if (err) {
     return callback(err);
   }
  if (authClient.createScopedRequired && authClient.createScopedRequired()) {
    authClient = authClient.createScoped([
      'https://www.googleapis.com/auth/cloud-platform'
    ]);
  }
  callback(null, authClient);
});
```
**New code**
```
const client = await auth.getClient({
  scopes: ['https://www.googleapis.com/auth/cloud-platform']
});
```

**Comment by jinmel** [comment]
any plans on closing this issue? :)
I am waiting for its release
