### ISSUE TITLE
http instrumentation cannot handle incoming requests with long request url path (>255)

### ISSUE THREAD

**Issue by jinmel** [census-instrumentation/opencensus-node#486]
Please answer these questions before submitting a bug report.

### What version of OpenCensus are you using?

0.0.11

### What version of Node are you using?

10

### What did you do?
If possible, provide a recipe for reproducing the error.

applied http instrumentation

### What did you see instead?

Error: Invalid TagValue: /v1/auth/oauth/google/callback?state=http://localhost:3001/signin&code=4/##############################################################&scope=email%20profile%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email
    at TagMap.set (node_modules/@opencensus/core/build/src/tags/tag-map.js:40:19)
    at ServerResponse.response.end (node_modules/@opencensus/instrumentation-http/build/src/http.js:177:34)
    at ServerResponse.end (node_modules/compression/index.js:107:21)

**Comment by mayurkale22** [comment]
This is happening because of https://github.com/census-instrumentation/opencensus-node/blob/master/packages/opencensus-core/src/tags/validation.ts#L32-L38. We have enforced 255 MAX_LENGTH limit on `TagKey` and `TagValue`. 

**What did you expect to see in this case?**
- a) Silently ignore the invalid tag(s) or 
- b) log a warning or error.

**Comment by vmarchaud** [comment]
A possible alternative would be to truncate the tag value ?

**Comment by jinmel** [comment]
@vmarchaud I agree to this solution.

**Comment by mayurkale22** [comment]
> A possible alternative would be to truncate the tag value ?

SGTM, Please review #515
