### ISSUE TITLE
Enable greenkeeper or renovate on this repo

### ISSUE THREAD

**Issue by ofrobots** [census-instrumentation/opencensus-node#58]
Let's make sure our dependencies are up to date.

**Comment by mayurkale22** [comment]
@ofrobots thanks for the issue. 

I am thinking of using  [Renovate Bot](https://github.com/apps/renovate) to keep  source code dependencies up-to-date using automated Pull Requests. I think renovate can help us focus on real work, instead of spending time on  #224, #226, #227, #229 and many more to come ##225)

**Cool renovate features:**
- [All of these choices for configuration](https://renovatebot.com/docs/configuration-options/)
- Scheduling -- you can have it run whenever, all at once, so we're not chasing PRs at all hours of the day
- It will update package-lock.json in a PR
- It can update packages & package-lock.json on a weekly basis
- It can rebase its own PRs automatically when the base branch is updated (e.g. when we merge another PR)
- It can automerge its own PRs after our tests pass (```default: false```)

/cc @bogdandrutu @justindsmith @OsvaldoRosado @jparsana @ofrobots any thoughts?

**Comment by ofrobots** [comment]
We use Renovate for all the Google Cloud Client libraries as well, so definitely +1 on using renovate. The bot does the grunt work and developers can focus on important things. Feel free to take a look at how we do things and copy. Here's an example repo: https://github.com/googleapis/google-auth-library-nodejs

**Comment by jparsana** [comment]
+1

@mayurkale22 I checked and renovate for opensource projects cost $0. Does that subscription work for OC node repo?

**Comment by mayurkale22** [comment]
> I checked and renovate for opensource projects cost $0. Does that subscription work for OC node repo?

**Yes, The Renovate Bot App is free for Open Source repositories** (while a paid plan from GitHub Marketplace is required for private repositories). I think once you install bot on OC-Node, will first receive an onboarding Pull Request to verify configs and what to expect stuff.

**Comment by mayurkale22** [comment]
Closed via https://github.com/census-instrumentation/opencensus-node/pull/233
